-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table PRODUCTS to save all the products and services offered.
-- APP_M_PROV_SELECC.PRODUCT definition

CREATE TABLE "APP_M_PROV_SELECC"."PRODUCT" 
   (	"PRODUCTID" NUMBER NOT NULL ENABLE, 
	"PRODUCTNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"AVERAGEPRICE" NUMBER(38,0) NOT NULL ENABLE, 
	"ACTIVITYID" NUMBER NOT NULL ENABLE, 
	"SELECTIONCRITERIAID" NUMBER NOT NULL ENABLE, 
	"ACTIVITYNAME" NUMBER(19,0), 
	 CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCTID")