-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table SELECTIONCRITERA to save selection criteria for suppliers.
-- APP_M_PROV_SELECC.SELECTIONCRITERIA definition

CREATE TABLE "APP_M_PROV_SELECC"."SELECTIONCRITERIA" 
   (	"SELECTIONCRITERIAID" NUMBER NOT NULL ENABLE, 
	"SELECTIONCRITERIANAME" VARCHAR2(50) NOT NULL ENABLE, 
	"SELECTIONCRITERIADESCRIPTION" VARCHAR2(200), 
	 CONSTRAINT "SELECTIONCRITERIA_PK" PRIMARY KEY ("SELECTIONCRITERIAID")