-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table SELECTIONACTIVITY to save all activities required to the products.
-- APP_M_PROV_SELECC.SELECTIONACTIVITY definition

CREATE TABLE "APP_M_PROV_SELECC"."SELECTIONACTIVITY" 
   (	"ACTIVITYID" NUMBER NOT NULL ENABLE, 
	"ACTIVITYNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"RESPONSIBLEAREAID" NUMBER, 
	 CONSTRAINT "SELECTIONACTIVITY_PK" PRIMARY KEY ("ACTIVITYID")