-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table SUPPLIERPRODUCTV1 as correlation table between tables supplier and product
-- APP_M_PROV_SELECC.SUPPLIERPRODUCTV1 definition

CREATE TABLE "APP_M_PROV_SELECC"."SUPPLIERPRODUCTV1" 
   (	"SUPPLIERID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRODUCTID" NUMBER(19,0) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SUPPLIERPRODUCTV1_PK" PRIMARY KEY ("ID")