-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table SUPPLIERS to save all the suppliers.
-- APP_M_PROV_SELECC.SUPPLIER definition

CREATE TABLE "APP_M_PROV_SELECC"."SUPPLIER" 
   (	"SUPPLIERID" NUMBER NOT NULL ENABLE, 
	"COMPANYNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(50) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(50), 
	"CELPHONE" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
	"SCORE" NUMBER NOT NULL ENABLE, 
	"CITY" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("SUPPLIERID")