-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates table TEMP_CONTRACTS to save contracts in a time frame by the package save_contracts
-- APP_M_PROV_SELECC.TEMP_CONTRACTS definition

CREATE GLOBAL TEMPORARY TABLE APP_M_PROV_SELECC.TEMP_CONTRACTS 
   (	CONTRACTID NUMBER, 
	CONTRACTDESCRIPTION VARCHAR2(50), 
	STARTDATE DATE, 
	FINISHDATE DATE, 
	CONTRACTSTATE VARCHAR2(50), 
	PRODUCTID NUMBER, 
	SUPPLIERID NUMBER
   ) ON COMMIT PRESERVE ROWS ;